# Generated by Django 5.2.17 on 2026-09-26 18:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lab.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("customer", models.CharField(max_length=200)),
                ("sample_code", models.CharField(blank=True, max_length=100)),
                ("test_series", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=lab.models.private_path)),
                ("sha256", models.CharField(max_length=64)),
                ("page_count", models.PositiveIntegerField()),
                ("form_type", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("ready", "Ready for review"),
                            ("failed", "Processing failed"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("processing_note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="lab.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="lab.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("template_version", models.CharField(default="proposed-v1", max_length=40)),
                ("snapshot", models.JSONField()),
                ("snapshot_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="lab.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-revision"],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=200)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("maximum", "Maximum"),
                            ("minimum", "Minimum"),
                            ("difference", "Difference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("source_clause", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("assumed", "Provisional"), ("confirmed", "Confirmed")],
                        default="assumed",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("code", "version"), name="unique_rule_version")
                ],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=200)),
                ("label", models.CharField(max_length=200)),
                ("value", models.TextField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("raw_value", models.TextField(blank=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[("scan", "Scanned document"), ("digital", "Digital entry")],
                        max_length=20,
                    ),
                ),
                ("page", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "bbox",
                    models.JSONField(
                        blank=True,
                        help_text="Normalised [left, top, right, bottom] on original page",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unreviewed", "Needs review"),
                            ("verified", "Verified"),
                            ("ambiguous", "Ambiguous"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="unreviewed",
                        max_length=20,
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lab.document",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="lab.job",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(fields=("job", "key"), name="unique_job_field")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("job", "sha256"), name="unique_job_document_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("job", "revision"), name="unique_report_revision"
            ),
        ),
    ]
