# Generated by Django 5.2.17 on 2026-09-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="rules",
            field=models.ManyToManyField(blank=True, related_name="jobs", to="lab.rule"),
        ),
    ]
