# Generated by Django 5.2.17 on 2026-09-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0002_job_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extraction_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
