# Generated by Django 5.2.17 on 2026-09-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0004_alter_report_options_job_report_scope_job_scope_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="approved_pdf",
            field=models.FileField(blank=True, upload_to="approved-reports/"),
        ),
    ]
