# Generated by Django 5.2.17 on 2026-09-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0005_report_approved_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("definition", models.JSONField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "version"), name="unique_report_template_version"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="report_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lab.reporttemplate",
            ),
        ),
    ]
