# Generated by Django 5.2.17 on 2026-09-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0006_reporttemplate_job_report_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="extraction_checkpoint",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
