# Generated by Django 5.2.17 on 2026-09-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0007_document_extraction_checkpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="delivery_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="report",
            name="delivery_recipient",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="report",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Not sent"),
                    ("sent", "Sent by staff"),
                    ("acknowledged", "Customer acknowledged"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="delivery_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
