# Generated by Django 5.2.17 on 2026-09-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0008_report_delivery_note_report_delivery_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insightdraft",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="insightdraft",
            name="processing_token",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
