# Generated by Django 5.2.17 on 2026-09-28 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0009_insight_processing_claim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "ordering": ["-revision"],
                "permissions": [
                    ("lock_report", "Lock engineer data for quality review"),
                    ("verify_report", "Verify a locked laboratory report as quality reviewer"),
                    ("approve_report", "Approve a laboratory report for export as HoD"),
                ],
            },
        ),
        migrations.AddField(
            model_name="report",
            name="engineer_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="engineer_locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locked_lab_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="issue_seal",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="report",
            name="quality_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="quality_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quality_verified_lab_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="return_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="report",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returned_lab_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
