# Generated by Django 5.2.17 on 2026-09-28 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0012_testrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="customer_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="customer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="file_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="job",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="job",
            name="request_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="requested_tests",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="sample_particulars",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_tests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="testrun",
            name="station",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
