# Generated by Django 5.2.17 on 2026-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0013_job_customer_address_job_customer_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="request_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
