# Generated by Django 5.2.17 on 2026-09-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0015_customernotification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="operation",
            field=models.CharField(
                choices=[
                    ("identity", "Direct value"),
                    ("maximum", "Maximum"),
                    ("minimum", "Minimum"),
                    ("difference", "Difference"),
                    ("ratio", "Ratio"),
                    ("percent_deviation", "Percent deviation from nominal"),
                    ("absolute_percent_change", "Absolute percent change"),
                    ("all_text", "All observations match"),
                ],
                max_length=40,
            ),
        ),
    ]
