# Generated by Django 5.2.17 on 2026-09-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0016_verdict_operations"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="approved_pdf_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="report",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Not sent"),
                    ("sending", "Sending / reconcile before retry"),
                    ("sent", "Sent"),
                    ("acknowledged", "Customer acknowledged"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
