# Generated by Django 5.2.17 on 2026-09-30 18:53

import hashlib
import hmac
import json

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_chain(apps, schema_editor):
    Event = apps.get_model("lab", "AuditEvent")
    previous_by_job = {}
    for event in Event.objects.using(schema_editor.connection.alias).order_by("pk").iterator():
        previous = previous_by_job.get(event.job_id, "0" * 64)
        payload = json.dumps(
            {
                "job": str(event.job_id),
                "actor": event.actor_id,
                "action": event.action,
                "details": event.details,
                "created_at": event.created_at.isoformat(),
                "previous_hash": previous,
            },
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=False,
            default=str,
        ).encode()
        digest = hmac.new(settings.AUDIT_CHAIN_KEY.encode(), payload, hashlib.sha256).hexdigest()
        Event.objects.using(schema_editor.connection.alias).filter(pk=event.pk).update(
            previous_hash=previous, event_hash=digest
        )
        previous_by_job[event.job_id] = digest


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0017_report_approved_pdf_sha256_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="event_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="previous_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill_chain, migrations.RunPython.noop),
    ]
