# Generated by Django 5.2.17 on 2026-09-30 19:07

import django.db.models.deletion
from django.db import migrations, models


def backfill_heads(apps, schema_editor):
    Event = apps.get_model("lab", "AuditEvent")
    Head = apps.get_model("lab", "AuditHead")
    count_by_job = {}
    last_by_job = {}
    for event in Event.objects.using(schema_editor.connection.alias).order_by("pk").iterator():
        count_by_job[event.job_id] = count_by_job.get(event.job_id, 0) + 1
        last_by_job[event.job_id] = event.event_hash
    Head.objects.using(schema_editor.connection.alias).bulk_create(
        [
            Head(job_id=job_id, last_hash=last_by_job[job_id], event_count=count)
            for job_id, count in count_by_job.items()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0018_auditevent_event_hash_auditevent_previous_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditHead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_hash",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        max_length=64,
                    ),
                ),
                ("event_count", models.PositiveIntegerField(default=0)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_head",
                        to="lab.job",
                    ),
                ),
            ],
        ),
        migrations.RunPython(backfill_heads, migrations.RunPython.noop),
    ]
