# Generated by Django 5.2.17 on 2026-10-02 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lab.models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0019_audithead"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to=lab.models.intake_path)),
                ("original_name", models.CharField(max_length=255)),
                ("sha256", models.CharField(max_length=64)),
                ("page_count", models.PositiveIntegerField()),
                ("candidate_form_type", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Classifying"),
                            ("triage", "Needs routing"),
                            ("routed", "Routed"),
                            ("failed", "Invalid PDF"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lab.job",
                    ),
                ),
                (
                    "routed_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lab.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
