# Generated by Django 5.2.17 on 2026-10-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0021_customerrequestdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="report_test_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
