# Generated by Django 5.2.17 on 2026-10-03 12:14

from django.db import migrations, models


def backfill_search_text(apps, schema_editor):
    Report = apps.get_model("lab", "Report")
    for report in Report.objects.all().iterator():
        snapshot = report.snapshot or {}
        values = [
            snapshot.get("customer", ""),
            snapshot.get("title", ""),
            snapshot.get("sample_code", ""),
            snapshot.get("test_series", ""),
            snapshot.get("file_number", ""),
        ]
        values += [
            str(field.get("label", "")) + " " + str(field.get("value", ""))
            for field in snapshot.get("fields", [])
        ]
        values += [
            str(rule.get("title", "")) + " " + str(rule.get("source_clause", ""))
            for rule in snapshot.get("calculations", [])
        ]
        Report.objects.filter(pk=report.pk).update(
            search_text=" ".join(str(value) for value in values if value)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0022_job_report_test_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="search_text",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(backfill_search_text, migrations.RunPython.noop),
    ]
